### ISSUE TITLE
Socket example using Antiphony

### ISSUE THREAD

**Issue by RossComputerGuy** [mitchellh/libxev#34]
I'm currently trying to use `libxev` to perform RPC calls in the background along with Antiphony. I tried looking at how `libxev` works and I cannot figure out how to create an event loop and have it handle Antiphony clients without blocking the main process.

**Comment by mitchellh** [comment]
I've never used antiphony so I'm not sure. If you can implement how antiphony sends/receives/connects then you'd just replace that with libxev calls. Antiphony would probably need some better async (in general, not Zig `async` keyword) support to support this, and since I haven't used it, I'm unsure how compatible it is.
